abstract class StateLayout{}
class InitLayoutState extends StateLayout{}
class ChangeBottomNavState extends StateLayout{}
class ProductImagePickerSuccessState extends StateLayout{}
class ProductImagePickerErrorState extends StateLayout{}
class ProductImageUploadLoadingState extends StateLayout{}
class ProductImageUploadSuccessState extends StateLayout{}
class ProductImageUploadErrorState extends StateLayout{}
class AddProductSuccessState extends StateLayout{}
class AddProductErrorState extends StateLayout{}
class EditProductSuccessState extends StateLayout{}
class EditProductErrorState extends StateLayout{}
class EditProductLoadingState extends StateLayout{}
class DownloadProductErrorState extends StateLayout{}
class AddProductLoadingState extends StateLayout{}
class GetProductErrorState extends StateLayout{}
class GetProductSuccessState extends StateLayout{}
class DeleteProductErrorState extends StateLayout{}
class DeleteProductSuccessState extends StateLayout{}
class DeleteCategoryErrorState extends StateLayout{}
class DeleteCategorySuccessState extends StateLayout{}
class GetProductLoadingState extends StateLayout{}
class CategoryImagePickerSuccessState extends StateLayout{}
class CategoryImagePickerErrorState extends StateLayout{}
class CategoryImageUploadLoadingState extends StateLayout{}
class CategoryImageUploadSuccessState extends StateLayout{}
class CategoryImageUploadErrorState extends StateLayout{}
class AddCategorySuccessState extends StateLayout{}
class AddCategoryErrorState extends StateLayout{}
class AddCategoryLoadingState extends StateLayout{}
class GetCategoryErrorState extends StateLayout{}
class GetCategorySuccessState extends StateLayout{}
class GetCategoryLoadingState extends StateLayout{}
class GetUserDataErrorState extends StateLayout{}
class GetUserDataSuccessState extends StateLayout{}
class GetCartLoadingState extends StateLayout{}
class GetCartErrorState extends StateLayout{}
class GetCartSuccessState extends StateLayout{}

class AddCartLoadingState extends StateLayout{}
class AddCartErrorState extends StateLayout{}
class AddCartSuccessState extends StateLayout{}
class DeleteItemCartErrorState extends StateLayout{}
class DeleteItemCartSuccessState extends StateLayout{}
class DeleteAllCartErrorState extends StateLayout{}
class DeleteAllCartSuccessState extends StateLayout{}
class UpdateItemCartErrorState extends StateLayout{}
class UpdateItemCartSuccessState extends StateLayout{}
class EmitToRebuildState extends StateLayout{}
class SearchState extends StateLayout{}
class AddOrderErrorState extends StateLayout{}
class AddOrderSuccessState extends StateLayout{}
class GetOrderErrorState extends StateLayout{}
class GetOrderLoadingState extends StateLayout{}
class GetOrderSuccessState extends StateLayout{}
class CancelOrderSuccessState extends StateLayout{}
class CancelOrderErrorState extends StateLayout{}
class DoneOrderSuccessState extends StateLayout{}
class DoneOrderErrorState extends StateLayout{}
class DeleteOrderSuccessState extends StateLayout{}
class DeleteOrderErrorState extends StateLayout{}
