abstract class StateLayout{}
class InitLayoutState extends StateLayout{}
class ChangeBottomNavState extends StateLayout{}
class ProductImagePickerSuccessState extends StateLayout{}
class ProductImagePickerErrorState extends StateLayout{}
class ProductImageUploadLoadingState extends StateLayout{}
class ProductImageUploadSuccessState extends StateLayout{}
class ProductImageUploadErrorState extends StateLayout{}
class AddProductSuccessState extends StateLayout{}
class AddProductErrorState extends StateLayout{}
class DownloadProductErrorState extends StateLayout{}
class AddProductLoadingState extends StateLayout{}
class GetProductErrorState extends StateLayout{}
class GetProductSuccessState extends StateLayout{}
class GetProductLoadingState extends StateLayout{}
class CategoryImagePickerSuccessState extends StateLayout{}
class CategoryImagePickerErrorState extends StateLayout{}
class CategoryImageUploadLoadingState extends StateLayout{}
class CategoryImageUploadSuccessState extends StateLayout{}
class CategoryImageUploadErrorState extends StateLayout{}
class AddCategorySuccessState extends StateLayout{}
class AddCategoryErrorState extends StateLayout{}

class AddCategoryLoadingState extends StateLayout{}
class GetCategoryErrorState extends StateLayout{}
class GetCategorySuccessState extends StateLayout{}
class GetCategoryLoadingState extends StateLayout{}
class GetUserDataErrorState extends StateLayout{}
class GetUserDataSuccessState extends StateLayout{}
class GetCartLoadingState extends StateLayout{}
class GetCartErrorState extends StateLayout{}
class GetCartSuccessState extends StateLayout{}
class AddCartLoadingState extends StateLayout{}
class AddCartErrorState extends StateLayout{}
class AddCartSuccessState extends StateLayout{}
class DeleteItemCartErrorState extends StateLayout{}
class DeleteItemCartSuccessState extends StateLayout{}
class UpdateItemCartErrorState extends StateLayout{}
class UpdateItemCartSuccessState extends StateLayout{}
